netbox/dns/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView, ImageAttachmentEditView
from ipam.views import ServiceEditView
from . import views


app_name = 'dns'
urlpatterns = [
    path('zones/', views.ZoneListView.as_view(), name='zone_list'), 
    path('zones/add/', views.ZoneEditView.as_view(), name='zone_add'),
    path('zones/import/', views.ZoneListView.as_view(), name='zone_import'),
    path('zones/delete/', views.ZoneBulkDeleteView.as_view(), name='zone_bulk_delete'),
    path('zones/<int:pk>', views.ZoneView.as_view(), name='zone_view'),
    path('zones/<int:pk>/edit/', views.ZoneEditView.as_view(), name='zone_edit'),
    path('zones/<int:pk>/delete/', views.ZoneDeleteView.as_view(), name='zone_delete'),



    path('record/', views.RecordListView.as_view(), name='record_list'), 
    path('record/add/', views.RecordEditView.as_view(), name='record_add'),
    path('record/import/', views.RecordListView.as_view(), name='record_import'),
    path('record/delete/', views.RecordBulkDeleteView.as_view(), name='record_bulk_delete'),
    path('record/<int:pk>', views.RecordView.as_view(), name='record_view'),
    path('record/<int:pk>/edit/', views.RecordEditView.as_view(), name='record_edit'),
    path('record/<int:pk>/delete/', views.RecordDeleteView.as_view(), name='record_delete'),
]

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
from netbox.api.views import APIRootView, StatusView
from netbox.views import HomeView, StaticMediaFailureView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site


openapi_info = openapi.Info(
    title="NetBox API",
    default_version='v2',
    description="API to access NetBox",
    terms_of_service="https://github.com/netbox-community/netbox",
    license=openapi.License(name="Apache v2 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
)

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('secrets/', include('secrets.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('user/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),
    path('dns/', include('dns.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/dns/', include('dns.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/secrets/', include('secrets.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),
    path('api/docs/', schema_view.with_ui('swagger'), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc'), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(), name='schema_swagger'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Admin
    path('admin/', admin_site.urls),
    path('admin/background-tasks/', include('django_rq.urls')),

    # Errors
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),
    path('admin/plugins/', include(plugin_admin_patterns))
]


if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

if settings.METRICS_ENABLED:
    _patterns += [
        path('', include('django_prometheus.urls')),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

handler500 = 'netbox.views.server_error'

netbox/users/api/urls.py
from netbox.api import OrderedDefaultRouter
from . import views


router = OrderedDefaultRouter()
router.APIRootView = views.UsersRootView

# Users and groups
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

# Permissions
router.register('permissions', views.ObjectPermissionViewSet)

# User preferences
router.register('config', views.UserConfigViewSet, basename='userconfig')

app_name = 'users-api'
urlpatterns = router.urls

netbox/users/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('api-tokens/', views.TokenListView.as_view(), name='token_list'),
    path('api-tokens/add/', views.TokenEditView.as_view(), name='token_add'),
    path('api-tokens/<int:pk>/edit/', views.TokenEditView.as_view(), name='token_edit'),
    path('api-tokens/<int:pk>/delete/', views.TokenDeleteView.as_view(), name='token_delete'),
    path('user-key/', views.UserKeyView.as_view(), name='userkey'),
    path('user-key/edit/', views.UserKeyEditView.as_view(), name='userkey_edit'),
    path('session-key/delete/', views.SessionKeyDeleteView.as_view(), name='sessionkey_delete'),

]

netbox/users/models.py
import binascii
import os

from django.contrib.auth.models import Group, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinLengthValidator
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from utilities.querysets import RestrictedQuerySet
from utilities.utils import flatten_dict


__all__ = (
    'AdminGroup',
    'AdminUser',
    'ObjectPermission',
    'Token',
    'UserConfig',
)


#
# Proxy models for admin
#

class AdminGroup(Group):
    """
    Proxy contrib.auth.models.Group for the admin UI
    """
    class Meta:
        verbose_name = 'Group'
        proxy = True


class AdminUser(User):
    """
    Proxy contrib.auth.models.User for the admin UI
    """
    class Meta:
        verbose_name = 'User'
        proxy = True


#
# User preferences
#

class UserConfig(models.Model):
    """
    This model stores arbitrary user-specific preferences in a JSON data structure.
    """
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name='config'
    )
    data = models.JSONField(
        default=dict
    )

    class Meta:
        ordering = ['user']
        verbose_name = verbose_name_plural = 'User Preferences'

    def get(self, path, default=None):
        """
        Retrieve a configuration parameter specified by its dotted path. Example:

            userconfig.get('foo.bar.baz')

        :param path: Dotted path to the configuration key. For example, 'foo.bar' returns self.data['foo']['bar'].
        :param default: Default value to return for a nonexistent key (default: None).
        """
        d = self.data
        keys = path.split('.')

        # Iterate down the hierarchy, returning the default value if any invalid key is encountered
        for key in keys:
            if type(d) is dict and key in d:
                d = d.get(key)
            else:
                return default

        return d

    def all(self):
        """
        Return a dictionary of all defined keys and their values.
        """
        return flatten_dict(self.data)

    def set(self, path, value, commit=False):
        """
        Define or overwrite a configuration parameter. Example:

            userconfig.set('foo.bar.baz', 123)

        Leaf nodes (those which are not dictionaries of other nodes) cannot be overwritten as dictionaries. Similarly,
        branch nodes (dictionaries) cannot be overwritten as single values. (A TypeError exception will be raised.) In
        both cases, the existing key must first be cleared. This safeguard is in place to help avoid inadvertently
        overwriting the wrong key.

        :param path: Dotted path to the configuration key. For example, 'foo.bar' sets self.data['foo']['bar'].
        :param value: The value to be written. This can be any type supported by JSON.
        :param commit: If true, the UserConfig instance will be saved once the new value has been applied.
        """
        d = self.data
        keys = path.split('.')

        # Iterate through the hierarchy to find the key we're setting. Raise TypeError if we encounter any
        # interim leaf nodes (keys which do not contain dictionaries).
        for i, key in enumerate(keys[:-1]):
            if key in d and type(d[key]) is dict:
                d = d[key]
            elif key in d:
                err_path = '.'.join(path.split('.')[:i + 1])
                raise TypeError(f"Key '{err_path}' is a leaf node; cannot assign new keys")
            else:
                d = d.setdefault(key, {})

        # Set a key based on the last item in the path. Raise TypeError if attempting to overwrite a non-leaf node.
        key = keys[-1]
        if key in d and type(d[key]) is dict:
            raise TypeError(f"Key '{path}' has child keys; cannot assign a value")
        else:
            d[key] = value

        if commit:
            self.save()

    def clear(self, path, commit=False):
        """
        Delete a configuration parameter specified by its dotted path. The key and any child keys will be deleted.
        Example:

            userconfig.clear('foo.bar.baz')

        Invalid keys will be ignored silently.

        :param path: Dotted path to the configuration key. For example, 'foo.bar' deletes self.data['foo']['bar'].
        :param commit: If true, the UserConfig instance will be saved once the new value has been applied.
        """
        d = self.data
        keys = path.split('.')

        for key in keys[:-1]:
            if key not in d:
                break
            if type(d[key]) is dict:
                d = d[key]

        key = keys[-1]
        d.pop(key, None)  # Avoid a KeyError on invalid keys

        if commit:
            self.save()


@receiver(post_save, sender=User)
@receiver(post_save, sender=AdminUser)
def create_userconfig(instance, created, **kwargs):
    """
    Automatically create a new UserConfig when a new User is created.
    """
    if created:
        UserConfig(user=instance).save()


#
# REST API
#

class Token(models.Model):
    """
    An API token used for user authentication. This extends the stock model to allow each user to have multiple tokens.
    It also supports setting an expiration time and toggling write ability.
    """
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='tokens'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    expires = models.DateTimeField(
        blank=True,
        null=True
    )
    key = models.CharField(
        max_length=40,
        unique=True,
        validators=[MinLengthValidator(40)]
    )
    write_enabled = models.BooleanField(
        default=True,
        help_text='Permit create/update/delete operations using this key'
    )
    description = models.CharField(
        max_length=200,
        blank=True
    )

    class Meta:
        pass

    def __str__(self):
        # Only display the last 24 bits of the token to avoid accidental exposure.
        return "{} ({})".format(self.key[-6:], self.user)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)

    def generate_key(self):
        # Generate a random 160-bit key expressed in hexadecimal.
        return binascii.hexlify(os.urandom(20)).decode()

    @property
    def is_expired(self):
        if self.expires is None or timezone.now() < self.expires:
            return False
        return True


#
# Permissions
#

class ObjectPermission(models.Model):
    """
    A mapping of view, add, change, and/or delete permission for users and/or groups to an arbitrary set of objects
    identified by ORM query parameters.
    """
    name = models.CharField(
        max_length=100
    )
    description = models.CharField(
        max_length=200,
        blank=True
    )
    enabled = models.BooleanField(
        default=True
    )
    object_types = models.ManyToManyField(
        to=ContentType,
        limit_choices_to=Q(
            ~Q(app_label__in=['admin', 'auth', 'contenttypes', 'sessions', 'taggit', 'users']) |
            Q(app_label='auth', model__in=['group', 'user']) |
            Q(app_label='users', model__in=['objectpermission', 'token'])
        ),
        related_name='object_permissions'
    )
    groups = models.ManyToManyField(
        to=Group,
        blank=True,
        related_name='object_permissions'
    )
    users = models.ManyToManyField(
        to=User,
        blank=True,
        related_name='object_permissions'
    )
    actions = ArrayField(
        base_field=models.CharField(max_length=30),
        help_text="The list of actions granted by this permission"
    )
    constraints = models.JSONField(
        blank=True,
        null=True,
        help_text="Queryset filter matching the applicable objects of the selected type(s)"
    )

    objects = RestrictedQuerySet.as_manager()

    class Meta:
        ordering = ['name']
        verbose_name = "permission"

    def __str__(self):
        return self.name

    def list_constraints(self):
        """
        Return all constraint sets as a list (even if only a single set is defined).
        """
        if type(self.constraints) is not list:
            return [self.constraints]
        return self.constraints

netbox/users/api/views.py
from django.contrib.auth.models import Group, User
from django.db.models import Count
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.routers import APIRootView
from rest_framework.viewsets import ViewSet

from netbox.api.views import ModelViewSet
from users import filters
from users.models import ObjectPermission, UserConfig
from utilities.querysets import RestrictedQuerySet
from utilities.utils import deepmerge
from . import serializers


class UsersRootView(APIRootView):
    """
    Users API root view
    """
    def get_view_name(self):
        return 'Users'


#
# Users and groups
#

class UserViewSet(ModelViewSet):
    queryset = RestrictedQuerySet(model=User).prefetch_related('groups').order_by('username')
    serializer_class = serializers.UserSerializer
    filterset_class = filters.UserFilterSet


class GroupViewSet(ModelViewSet):
    queryset = RestrictedQuerySet(model=Group).annotate(user_count=Count('user')).order_by('name')
    serializer_class = serializers.GroupSerializer
    filterset_class = filters.GroupFilterSet


#
# ObjectPermissions
#

class ObjectPermissionViewSet(ModelViewSet):
    queryset = ObjectPermission.objects.prefetch_related('object_types', 'groups', 'users')
    serializer_class = serializers.ObjectPermissionSerializer
    filterset_class = filters.ObjectPermissionFilterSet


#
# User preferences
#

class UserConfigViewSet(ViewSet):
    """
    An API endpoint via which a user can update his or her own UserConfig data (but no one else's).
    """
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return UserConfig.objects.filter(user=self.request.user)

    def list(self, request):
        """
        Return the UserConfig for the currently authenticated User.
        """
        userconfig = self.get_queryset().first()

        return Response(userconfig.data)

    def patch(self, request):
        """
        Update the UserConfig for the currently authenticated User.
        """
        # TODO: How can we validate this data?
        userconfig = self.get_queryset().first()
        userconfig.data = deepmerge(userconfig.data, request.data)
        userconfig.save()

        return Response(userconfig.data)

netbox/templates/users/api_tokens.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}API Tokens{% endblock %}

{% block usercontent %}
    <div class="row">
        <div class="col-md-12">
            {% for token in tokens %}
                <div class="panel panel-{% if token.is_expired %}danger{% else %}default{% endif %}">
                    <div class="panel-heading">
                        <div class="pull-right noprint">
                            <a class="btn btn-xs btn-success copy-token" data-clipboard-target="#token_{{ token.pk }}">Copy</a>
                            {% if perms.users.change_token %}
                                <a href="{% url 'user:token_edit' pk=token.pk %}" class="btn btn-xs btn-warning">Edit</a>
                            {% endif %}
                            {% if perms.users.delete_token %}
                                <a href="{% url 'user:token_delete' pk=token.pk %}" class="btn btn-xs btn-danger">Delete</a>
                            {% endif %}
                        </div>
                        <i class="mdi mdi-key"></i>
                        <samp><span id="token_{{ token.pk }}">{{ token.key }}</span></samp>
                        {% if token.is_expired %}
                            <span class="label label-danger">Expired</span>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <small class="text-muted">Created</small><br />
                                <span title="{{ token.created }}">{{ token.created|date }}</span>
                            </div>
                            <div class="col-md-4">
                                <small class="text-muted">Expires</small><br />
                                {% if token.expires %}
                                    <span title="{{ token.expires }}">{{ token.expires|date }}</span>
                                {% else %}
                                    <span>Never</span>
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <small class="text-muted">Create/edit/delete operations</small><br />
                                {% if token.write_enabled %}
                                    <span class="label label-success">Enabled</span>
                                {% else %}
                                    <span class="label label-danger">Disabled</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if token.description %}
                            <br /><span>{{ token.description }}</span>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p>You do not have any API tokens.</p>
            {% endfor %}
            {% if perms.users.add_token %}
                <a href="{% url 'user:token_add' %}" class="btn btn-primary">
                    <span class="mdi mdi-plus-thick" aria-hidden="true"></span>
                    Add a token
                </a>
            {% else %}
                <div class="alert alert-info text-center" role="alert">
                    You do not have permission to create new API tokens. If needed, ask an administrator to enable token creation for your account or an assigned group.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
new ClipboardJS('.copy-token');
</script>
{% endblock %}

netbox/templates/users/base.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 col-md-2 col-md-offset-1">
        <ul class="nav nav-pills nav-stacked">
            <li{% if active_tab == "profile" %} class="active"{% endif %}>
                <a href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li{% if active_tab == "preferences" %} class="active"{% endif %}>
                <a href="{% url 'user:preferences' %}">Preferences</a>
            </li>
            {% if not request.user.ldap_username %}
                <li{% if active_tab == "change_password" %} class="active"{% endif %}>
                    <a href="{% url 'user:change_password' %}">Change Password</a>
                </li>
            {% endif %}
            <li{% if active_tab == "api_tokens" %} class="active"{% endif %}>
                <a href="{% url 'user:token_list' %}">API Tokens</a>
            </li>
            <li{% if active_tab == "userkey" %} class="active"{% endif %}>
                <a href="{% url 'user:userkey' %}">User Key</a>
            </li>
        </ul>
    </div>
	<div class="col-sm-9 col-md-8">
        {% block usercontent %}{% endblock %}
	</div>
</div>
{% endblock %}

netbox/templates/users/change_password.html
{% extends 'users/base.html' %}
{% load form_helpers %}

{% block title %}Change Password{% endblock %}

{% block usercontent %}
    <form action="." method="post" class="form form-horizontal col-md-10 col-md-offset-1">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="panel panel-danger">
                <div class="panel-heading"><strong>Errors</strong></div>
                <div class="panel-body">
                    {{ form.non_field_errors }}
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Password</strong></div>
            <div class="panel-body">
                {% render_field form.old_password %}
                {% render_field form.new_password1 %}
                {% render_field form.new_password2 %}
            </div>
        </div>
        <div class="text-right">
            <button type="submit" name="_update" class="btn btn-primary">Update</button>
            <a href="{% url 'user:profile' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
{% endblock %}

netbox/templates/users/preferences.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}User Preferences{% endblock %}

{% block usercontent %}
    {% if preferences %}
        <form method="post" action="">
            {% csrf_token %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><input type="checkbox" class="toggle" title="Toggle all"></th>
                        <th>Preference</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for key, value in preferences.items %}
                        <tr>
                            <td class="min-width"><input type="checkbox" name="pk" value="{{ key }}"></td>
                            <td><samp>{{ key }}</samp></td>
                            <td><samp>{{ value }}</samp></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit" class="btn btn-danger">
                <span class="mdi mdi-trash-can-outline" aria-hidden="true"></span> Clear Selected
            </button>
        </form>
    {% else %}
        <h3 class="text-muted text-center">No preferences found</h3>
    {% endif %}
{% endblock %}

netbox/templates/users/profile.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}User Profile{% endblock %}

{% block usercontent %}
    <small class="text-muted">User login</small>
    <h5>{{ request.user.username }}</h5>
    <small class="text-muted">Full name</small>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <small class="text-muted">Email</small>
    <h5>{{ request.user.email }}</h5>
    <small class="text-muted">Registered</small>
    <h5>{{ request.user.date_joined }}</h5>
    <small class="text-muted">Groups</small>
    <h5>{{ request.user.groups.all|join:', ' }}</h5>
    <small class="text-muted">Admin access</small>
    <h5>{{ request.user.is_staff|yesno|capfirst }}</h5>
{% endblock %}

netbox/templates/users/sessionkey_delete.html
{% extends 'generic/object_delete.html' %}

{% block message %}
    <p>Are you sure you want to delete your session key?</p>
{% endblock %}

netbox/templates/users/userkey.html
{% extends 'users/base.html' %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if object %}
        <div class="pull-right noprint">
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-warning">
                <span class="mdi mdi-pencil" aria-hidden="true"></span>
                Edit user key
            </a>
        </div>
        <h4>
            Your user key is:
            {% if object.is_active %}
                <span class="label label-success">Active</span>
            {% else %}
                <span class="label label-danger">Inactive</span>
            {% endif %}
        </h4>
        {% include 'inc/created_updated.html' %}
        {% if not object.is_active %}
            <div class="alert alert-warning" role="alert">
                <i class="mdi mdi-alert"></i>
                Your user key is inactive. Ask an administrator to enable it for you.
            </div>
        {% endif %}
        <pre>{{ object.public_key }}</pre>
        <hr />
        {% if object.session_key %}
            <div class="pull-right noprint">
                <a href="{% url 'user:sessionkey_delete' %}" class="btn btn-danger">
                    <span class="mdi mdi-trash-can-outline" aria-hidden="true"></span>
                    Delete session key
                </a>
            </div>
            <h4>Session key: <span class="label label-success">Active</span></h4>
            <small class="text-muted">Created {{ object.session_key.created }}</small>
        {% else %}
            <h4>No active session key</h4>
        {% endif %}
    {% else %}
        <p>You don't have a user key on file.</p>
        <p>
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-primary">
                <span class="mdi mdi-plus-thick" aria-hidden="true"></span>
                Create a User Key
            </a>
        </p>
    {% endif %}
{% endblock %}

netbox/templates/users/userkey_edit.html
{% extends 'users/base.html' %}
{% load static %}
{% load form_helpers %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if object.is_active %}
        <div class="alert alert-danger" role="alert">
            <strong>Warning:</strong> Changing your public key will require your user key to be re-activated by another
            user. You will be unable to retrieve any secrets until your key has been reactivated.
        </div>
    {% endif %}
    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.public_key %}
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-sm-6 col-md-6">
                    <button type="button" class="btn btn-info" id="generate_keypair">Generate a New Key Pair</button>
                </div>
                <div class="col-sm-6 col-md-6 text-right">
                    <button type="submit" name="_update" class="btn btn-primary">Save</button>
                    <a href="{% url 'user:userkey' %}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="new_keypair_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="new_keypair_modal_title">
                        New RSA Key Pair
                    </h4>
                </div>
                <div class="modal-body">
                    <strong>New Public Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_pubkey" style="height: 250px;"></textarea>
                    </div>
                    <strong>New Private Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_privkey" style="height: 250px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-danger" id="use_new_pubkey" data-dismiss="modal">I have saved my new private key</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}